### PR TITLE
No switch

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Implements the algorithm proposed in https://github.com/datrs/varinteger/pull/1. Keeps the single branch just like in the proposed impl, and also keeps all arithmatic in `u32`. Thanks!

cc/ @mwarning

### CODE REVIEW

**Comment by mwarning** [comment]
hm, I haven't done any benchmarks on the code. And you have also introduced an if. Not sure if the compiler can remove it.

**Comment by yoshuawuyts** [comment]
@mwarning I believe the branch was already there in the form of `(lo == 0)`, which returns a boolean that is then cast to a `u32`. I'm not sure if what I wrote is equivalent though; I'm going to check.

**Comment by yoshuawuyts** [comment]
Got the x86 assembly output here. I believe they are exactly the same, but maybe I'm missing something. Results from https://godbolt.org.

__edit:__ it looks like in the initial version the branch wasn't compiled away either. ` cmp eax, 1` shows up in both versions.

## Original Implementation
```asm
example::length:
  push rbp
  mov rbp, rsp
  test rdi, rdi
  je .LBB0_1
  bsr rcx, rdi
  xor rcx, 63
  jmp .LBB0_3
.LBB0_1:
  mov ecx, 64
.LBB0_3:
  mov eax, 64
  sub eax, ecx
  cmp eax, 1
  adc eax, 0
  add eax, 6
  imul rcx, rax, 613566757
  shr rcx, 32
  sub eax, ecx
  shr eax
  add eax, ecx
  shr eax, 2
  pop rbp
  ret
```

## Implementation from this PR
```asm
example::length:
  push rbp
  mov rbp, rsp
  test rdi, rdi
  je .LBB0_1
  bsr rcx, rdi
  xor rcx, 63
  jmp .LBB0_3
.LBB0_1:
  mov ecx, 64
.LBB0_3:
  mov eax, 64
  sub eax, ecx
  cmp eax, 1
  adc eax, 0
  add eax, 6
  imul rcx, rax, 613566757
  shr rcx, 32
  sub eax, ecx
  shr eax
  add eax, ecx
  shr eax, 2
  pop rbp
  ret
```

**Comment by mwarning** [comment]
I get a different output. But I don't know how to enable optimizations on godbolt.org.
Anyway, `(lo == 0) as usize` represents no branch and the compiler should not make it into a branch. But maybe the compiler can optimize your change to be branchless.
Whatever :>

**Comment by yoshuawuyts** [comment]
@mwarning pass the `-O` flag into the compiler to enable optimizations :sparkles:. Looks like either way the output is cutting the instruction cost from `40` > `20` so it's a net win overall :grin:

**Pull request merged**
